### ISSUE TITLE
Versione 2.5.1 don't start

### ISSUE THREAD

**Issue by fabiograz** [r3-team/r3#12]
Hi,
I downloaded version 2.5.1 on Windows and launched start_portable.cmd but I get this error:
![c8Mi8R3P4n](https://user-images.githubusercontent.com/11799153/143677929-e9036139-127f-4dc6-80a6-f89475d757f4.png)

Thanks,
Fabio.

**Comment by r3-gabriel** [comment]
Hello Fabio,

The message seems to roughly translate to "file r3.exe could not be found". Is "r3.exe" inside the folder "r3-2.5.1"?

If yes, could you please check your local antivirus? Sometimes applications that start network services are wrongly classified as malware. The file is then sent to quarantine or access to it blocked.

Warm regards,

Gabriel

**Comment by fabiograz** [comment]
Hi,
R3.exe Is not in the folder. I've checked the zip also and It there isn't.

Fabio.

**Comment by r3-gabriel** [comment]
Hello Fabio,

The installer/portable versions definitely include the r3.exe file. Please check your antivirus logs. When you open a zip file with the Windows Explorer directly, Windows can and will remove files it assumes are malware.

You might need to re-download the zip file after you have configured your antivirus.

It is annoying but apparently some malware behaves similar to web server applications, which are written in Golang. We actively work on not being falsely flagged as malware (digitally signing our executables, notifying Microsoft about false positives, etc.), but this does not always work.


Warm regards,

Gabriel

**Comment by fabiograz** [comment]
Ok, I0ve downloaded the source code from github and not the portable version from rei3.de site. 

Why don't put the portable version to github?

Thanks.

**Comment by r3-gabriel** [comment]
The portable version is on Github. If you compile REI3 you get a binary that is both used for the portable and installed version on Windows - there is no difference.

Or do you mean the pre-compiled versions? If so, it would make no difference, whether you download the files from Github or rei3.de. We only have these files on rei3.de as it would be redundant to also host them on Github.

The portable package from our website definitely contains all required files, including `r3.exe` - I triple-checked. If you are having issues opening the file, it is because of local circumstances (antivirus from my experience).

Warm regards,

Gabriel
