### ISSUE TITLE
ReferenceError: RELATION_NAME is not defined

### ISSUE THREAD

**Issue by gizocz** [r3-team/r3#32]
I have two Relations with the 1:1 relation and a Form with Fields from both Relations. The Form has a frontend Function assigned and inside the Function calls app.get_field_value() to read the values from both Relations.

It works well if both Relations are inside one Application. However, if the two Relations are in different dependent Applications, an error "ReferenceError: THE_OTHER_RELATION is not defined" occured.

**Comment by r3-gabriel** [comment]
I was able to replicate this issue and find the underlying cause:

![image](https://user-images.githubusercontent.com/91060542/220084832-b4137992-85b7-4fe0-9d84-b1206d6d197d.png)
The screenshot above shows two field references (one internal and one external).

![image](https://user-images.githubusercontent.com/91060542/220085059-898fbdc4-026e-43be-a3f9-c4354675db49.png)
Enabling the preview, we see that only the one referencing an internal attribute is resolved.

This is definitely a bug in the JS function editor. Once fixed, you will have to save the JS function again so that all placeholders are correctly resolved.

Thank you for this report!

**Comment by r3-gabriel** [comment]
I´ve found a good solution for this issue. It might take a short while for the next release to come out. Do you require this fix urgently?

**Comment by gizocz** [comment]
I have already rewritten my app to workaround this bug, so it is not urgent for me now. Better, please, implement the feature "custom validate function" #31 :)
Thank you

**Comment by r3-gabriel** [comment]
Its planned to be part of the next release. It should come out with 3.3.
