### ISSUE TITLE
preset record selector from dependant application

### ISSUE THREAD

**Issue by gizocz** [r3-team/r3#34]
There is a preset record selector in Forms builder -> Form settings -> States -> Conditions. But the selector offers only preset records from the current Application, not from the Build-on Applications.  (bug or feature?)

It would be great if such preset record selector will be available also in Frontend/Backend functions. (feature request)

**Comment by r3-gabriel** [comment]
I´ve had a look. We can easily enable the preset selector for build-on apps - but I ran into an issue during implementation. We do dependency checking between apps so that you cannot easily break your application. The problem is that filters (form state conditions are just limited versions of filters) are used everywhere und can in some contexts use sub-queries which can also use sub-queries and so on. I will need to implement recursive checks to make sure that you cannot remove an application that any of your preset-filters still rely on.

It should be rather straightforward, adding preset record placeholders in functions, when I can solve the issue of the recursive checks.

**Comment by r3-gabriel** [comment]
We´ve implemented the required checks - in the next release, you will be able to access preset records from built-on applications in form state conditions and filters.

Inside front- & backend functions, you´ll also be able to retrieve the current record ID for a preset with a new instance function, called `get_preset_record_id()`.
