### ISSUE TITLE
Filter criteria and column name do not match when setting a column name for the table

### ISSUE THREAD

**Issue by Martin-Bonn** [r3-team/r3#45]
As you see e.g. in the ticket app, the column name is "Erzeugt von", but the filter criteria is "Anzeigename", "Durchgeführte Operationen" is "Anmerkung Änderungsgrund", which is confusing for the user. 

Is your app builds on another app, e.g. the organization app, you also don't have control over over the attribute name to change it at the source.

![grafik](https://github.com/r3-team/r3/assets/108742493/e46c232e-b50e-41eb-af83-e5106f1a521b)

**Comment by r3-gabriel** [comment]
You are right, there is a disconnect there. The custom filters work with the attributes of the given query (and their titles), but the displayed columns in the list can be modified in various ways (overwritten, batched, filled via sub query) and so can be quite different.

The issue is a bit of a historical artifact - as list options expanded but the filters were not in the same way. We´ll look at options on how to address this. Thank you for the report.

**Comment by r3-gabriel** [comment]
Adressed with commit: https://github.com/r3-team/r3/commit/a5db4e20f5bdeb583e79d28a3df04aa7e1e7879c
