### ISSUE TITLE
app.block_inputs(true) does not block list actions

### ISSUE THREAD

**Issue by TechInterMezzo** [r3-team/r3#59]
When I use app.block_inputs(true) on a form it doesn't disable the new button of list fields.
Is this a bug or am I using the function for the wrong purpose?

I am blocking the inputs while checking/waiting for the result of an async rest call from the backend.

**Comment by r3-gabriel** [comment]
Actions on list fields (like new, edit or delete) are not considered inputs, as they do not affect the record being handled by the current form.

**Comment by TechInterMezzo** [comment]
That sounds plausible.
Maybe showing an overlay with a text or even a loading animation could help. It would prevent further interaction and signal a long running async process.

But maybe that is against your intended design.

**Comment by r3-gabriel** [comment]
It´s less about design intent and more about not being able to spend enough time to redesign larger components. Some things we can easily add to the current structure without breaking anything - other features require large redesigns and new concepts.

We are very aware of the limitations we currently have - we build a lot of REI3 applications for customers and also need to deal with what is possible and what is not. This is the case for any software of course - but it´s especially fun when you know that you could solve so many things with enough dev time.

But it´s good that people let us know, what features they are missing so that we can plan and prioritize accordingly. Please feel free to always share what is missing or sub-optimal for your use cases :)
