### ISSUE TITLE
Open record with menu entry

### ISSUE THREAD

**Issue by TechInterMezzo** [r3-team/r3#61]
Is it possible to open a specific record by clicking a menu entry?
I linked a relation to the user login.
So now every user can have a record assigned to his login.
It would be great if every user could open his own record by clicking a menu entry.
The only thing I found out is how to create a form with a list that can filter entries by the login id.
But I would like to skip that listing step for this single record and directly open it.

Maybe a frontend function that gets triggered before the form loading could be used to set/change the record id to load.

I could also think of another new feature: Assigning a frontend function instead of a form to a menu entry. That way I could use the app.form_open function.

**Comment by r3-gabriel** [comment]
Using a frontend function running after form load would address your requirement. You would open a naked form, the after load function executes, reading the current login ID and opening up the same or a different form with the desired record. To retrieve the connected record ID (the record connected to the current login), you can use a backend function call.

**Comment by TechInterMezzo** [comment]
Thank you for giving a solution. I am now also using a collection with a filter for the current login id to cache the record id.
R3 might the best open source low code system I have seen so far. Do you accept PR's if they fit your product?

**Comment by r3-gabriel** [comment]
Cool that you have found collections useful for your case - they are especially helpful for static data, which records connected to logins tend to be.

Thank you for the kind words. It´s a lot, but satisfying work :)

Regarding PRs: Yes of course. The challenge is that most people want changes in the frontend, which are quite hard to do right; low code tools are complex beasts, not just due to technical complexities but also because of consequences for planned features, overall usability and the knowledge what enterprise customers currently rely on.

But if you can navigate the complexities of the source code, please feel free to submit. We will let you know, if your changes break something or might have unintended consequences.

**Comment by r3-gabriel** [comment]
Closing issue as there is no open task or request to answer.
